### ISSUE TITLE
Add additional exercises

### ISSUE THREAD

**Issue by BNAndras** [exercism/vimscript#172]
Exercises that should be ported over in 2024

- [ ] Bank Account
- [ ] Circular Buffer
- [ ] Diamond
- [ ] Food Chain
- [ ] Kindergarten Garden
- [ ] Knapsack
- [ ] Linked List
- [ ] Matching Brackets
- [ ] Meetup (discuss before tackling)
- [ ] Minesweeper
- [ ] Parallel Letter Frequency
- [ ] Pascal's Triangle
- [ ] Pig Latin
- [ ] Sieve
- [ ] Spiral Matrix
- [ ] Yacht
- [ ] Zebra Puzzle
- [x] Acronym
- [x] All Your Base
- [x] Armstrong Numbers
- [x] Binary Search
- [x] Bottle Song
- [x] Clock
- [x] Collatz Conjecture
- [x] Custom Set
- [x] D&D Character
- [x] Darts
- [x] Flatten Array
- [x] Grains
- [x] High Scores
- [x] House
- [x] Isogram
- [x] List Ops
- [x] Luhn
- [x] Matrix
- [x] Micro Blog
- [x] Perfect Numbers
- [x] Protein Translation
- [x] Proverb
- [x] Queen Attack
- [x] Resistor Color
- [x] Resistor Color Duo
- [x] Reverse String
- [x] Robot Simulator
- [x] Rotational Cipher
- [x] Run Length Encoding
- [x] Secret Handshake
- [x] Series
- [x] Simple Linked List
- [x] Space Age
- [x] Square Root
- [x] Strain
- [x] Sublist
- [x] Transpose
- [x] Two Fer

**Comment by kotp** [comment]
Go for it!  I can test and review.

**Comment by BNAndras** [comment]
For the purposes of this PR, `isogram` and `space-age` will be replaced by whatever exercises get chosen in https://forum.exercism.org/t/select-featured-exercises-for-december-diversions/

**Comment by kotp** [comment]
I edited the checklist in the original message to reflect choice pending.

**Comment by BNAndras** [comment]
Okay, it looks like we're adding 'all-your-base`, 'dnd-character`, `flatten-array`, `run-length-encoding`, and `queen-attack`. I'll work on dnd-character, flatten-array, and possibly queen-attack next week.  I have family in town for the next two weekends but I think I can get all-your-base the week after. I've solved that a few times so it shouldn't be too bad, but I've definitely had trouble with run-length-encoding in Python. I may need some help with that if you're available.

**Comment by BNAndras** [comment]
Okay, we're ahead of schedule so I'll add isogram and space-age next. I'll throw in protein-translation while it's fresh in my head from porting it to CFML.

**Comment by kotp** [comment]
Three left... Very nice!

**Comment by BNAndras** [comment]
> Three left... Very nice!

You say that but then I keep finding more to port. :)

**Comment by kotp** [comment]
> > Three left... Very nice!
> 
> You say that but then I keep finding more to port. :)

And yet, there is still only three left! 🔧

**Comment by BNAndras** [comment]
I'll start on Food Chain later this month. I have a hunch that it might come up in #48in24 so it'd be good to start rolling on that.

**Comment by BNAndras** [comment]
https://docs.google.com/spreadsheets/d/1X00y60Z6BqYbTMnmmuMYzMoS0eO4KKquSWq2ijXb4Qo/edit#gid=0 lists several exercises to be featured over the next few months. I've updated the tracking list up top with the exercises I saw that we don't have yet if anyone wants to claim an exercise.

**Comment by BNAndras** [comment]
I'm going to retire this thread since it's superseded by https://exercism.org/challenges/48in24/implementation_status. I'll start a fresh issue in 2025 if we still have practice exercises we want to port.

**Comment by kotp** [comment]
> I'll start a fresh issue in 2025 if we still have practice exercises we want to port.

Already planning 20 months out?
