### ISSUE TITLE
Consider consistency for the exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/vimscript#2]
- Is there a style guide for Vim script?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- Is there a common convention for filenames? If not, what should our convention be?

Note that this is about the exercises (the test suites and code examples), not people's solutions.

**Comment by mhinz** [comment]
> Is there a style guide for Vim script?

The only one I know of: https://google.github.io/styleguide/vimscriptguide.xml. They use it for their own projects, e.g. https://github.com/google/vim-maktaba.

I do not necessarily agree with everything mentioned in that guide, but the things I don't agree with, shouldn't occur in Exercism problems anyway.

> Is there a linter? Are there many? Should we use one?

Most VimL projects I know use https://github.com/Kuniwak/vint. That's usually all you need if checking for best practices.

> Is there a common convention for filenames?

snake_case!

All in all the ecosystem around VimL (or Vim script) is not as huge as for "real" programming languages.

**Comment by kytrinyx** [comment]
These are great. I think for the linter we should use Kuniwak/vint on this repo (and fail the build on failed linting, maybe), and then make it a loose recommendation for people doing the exercises.
