### ISSUE TITLE
Update Grains exercise

### ISSUE THREAD

**Issue by BNAndras** [exercism/vimscript#256]
https://forum.exercism.org/t/odd-arithmetic-in-grains/8662/23

The example for Grains needs to be updated so the Square and Total functions return a string.

The exercise difficulty needs to be updated to medium.

The "grains on square 64" and "returns the total number of grains on the board" tests need to be updated to use the correct expected values as strings.

**Comment by kotp** [comment]
Apparently I closed it as a result of misinterpretation involving 269 being merged.

**Comment by kotp** [comment]
Addressed via #326 

I believe this is now "hard" as it uses strings to get beyond the integer limitations, and could theoretically be solved using 8 bit vim, if there were such a thing.

**Comment by BNAndras** [comment]
If you’re referring to the difficulty displayed on the site, a difficulty of 5 is a medium exercise. It needs to be 7 or higher to be a hard exercise.
