### ISSUE TITLE
Incorrect CLI command for checking out first exercise

### ISSUE THREAD

**Issue by codeinabox** [exercism/vimscript#259]
When I was on the page https://exercism.org/tracks/vimscript, it told me the CLI command to use is `exercism download --exercise=hello-world --track=Vim script`. This is incorrect and should be `exercism download --exercise=hello-world --track=vimscript`.

**Comment by BNAndras** [comment]
I can't seem to replicate this. I see `exercism download --track=vimscript --exercise=hello-world`

**Comment by codeinabox** [comment]
It's a tricky one to recreate as it's only shown when you first start the track

**Comment by BNAndras** [comment]
@ErikSchierboom, thoughts?

**Comment by BNAndras** [comment]
I joined the Standard ML track and got `exercism download --exercise=hello-world --track=Standard ML`. I think the new modal is pulling in the track name not the track slug.

**Comment by ErikSchierboom** [comment]
PR opened: https://github.com/exercism/website/pull/6694

**Comment by codeinabox** [comment]
Thank you for fixing this so quickly
