### ISSUE TITLE
Implement Continuous Integration

### ISSUE THREAD

**Issue by kytrinyx** [exercism/vimscript#3]
Implement a test suite that can run both locally and on Travis CI, that verifies that the example code passes the test suite for each exercise.

Things to consider:

If some tests are marked as skipped or pending in some way, then CI should remove these annotations so that all the tests run against the example, not just the first test.

If we need to rewrite the files in any way, we should copy the exercise to a tmp directory first, so that we don't accidentally end up committing changes that are just for continuous integration or testing purposes.

We should make it possible to test just one exercise at a time, because testing everything can take a while, and very often people are just working on one exercise and will only need to run the full test suite before committing the change.

**Comment by mhinz** [comment]
I made good experiences with https://github.com/junegunn/vader.vim. It's also the only solution that is purely written in VimL. Other solutions rely on another scripting language like Ruby.

Vader acts like a normal Vim plugin and basically just exports a new command.

Example:

```vim
" exercise.vim
function! Test() abort
  return "this works"
endfunction
```

```vim
" exercise.vader
Execute (Test returns expected string):
  AssertEqual Test(), "this works"
  AssertEqual Test(), "oh noes!"
```

You would run the tests like this (depending on what files is opened at the moment):

- From **exercise.vim**:
  1. `:source %` (source current file and make the function available to Vim)
  1. `:Vader exercise.vader` (run tests)
- from **exercise.vader**:
  1. `:source exercise.vim`
  1. `:Vader` (run currently opened tests)

Output:

```
Starting Vader: 1 suite(s), 1 case(s)
  Starting Vader: /private/tmp/exercise.vader
    (1/1) [EXECUTE] Test returns expected string
    (1/1) [EXECUTE] (X) 'oh noes!' should be equal to 'this works'
  Success/Total: 0/1
Success/Total: 0/1 (assertions: 1/2)
Elapsed time: 0.021283 sec.
```

**Comment by kytrinyx** [comment]
> It's also the only solution that is purely written in VimL. Other solutions rely on another scripting language like Ruby.

That's an excellent point. I'm all for something that is pure Vim script

**Comment by kotp** [comment]
Travis seems to be set up, and the script that ran for Travis in PR #25 returned with a 0, but at this moment, it still says that it is pending.

![selection_007](https://cloud.githubusercontent.com/assets/16747/26531737/9ff8c2ce-43bd-11e7-9c07-05c3f995759a.png)

**Comment by mhinz** [comment]
@kotp 

Not sure if it was GitHub who wasn't picking it up or Travis who never sent the message. Whatever it was, I restarted the job using Travis's web interface and it's all green now!

**Comment by kotp** [comment]
OK, looks good.  Is the vim-gtk a requirement, or should we use vim-nox instead?  Something a little bit lighter maybe faster to install as it should be a little lighter on requirements.  If it is a 'timing issue', this may help.

**Comment by mhinz** [comment]
Oh, no, that issue had nothing to do with this repo. It was the fault of either GitHub or TravisCI. I saw similar issues before, but they happen very rarely.

`vim-gtk` is used for two reasons:

1. It's very common for Debian/Ubuntu users to use that package (or `gtk-gnome` which isn't much different).
2. Vim has many compile-time options and the advantage of `vim-gtk` over `vim-nox` is in our case not the additional GUI support, but that it comes with the "huge feature set". `vim-nox` lacks many things a power user would expect.

For reference: `vim --version` shows which feature set was compiled in in the first lines, e.g. "Huge version without GUI" in my case. `:help :version` shows which "size" is needed for which features.
