### ISSUE TITLE
Helpful tip to watch for file changes and run tests from command line

### ISSUE THREAD

**Issue by agentofuser** [exercism/vimscript#82]
This was very useful to me, so leaving here in case it helps others.

After installing [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli), I added a file `watch.zsh` under `~/Exercism/vimscript` with this content:

```zsh
#!/usr/bin/env zsh
chokidar "*/*.vim" -c "cd \`dirname {path}\` && nvim -c 'source % | Vader! *.vader' *.vim && echo Success || echo Failure"
```

After giving it executable permission with `chmod +x watch.zsh`, I run `./watch.zsh` on one terminal then edit the files in vim. Every time the file is saved, the tests are re-run. Hope it helps.

**Comment by BNAndras** [comment]
Thanks for the tip. I think we want to keep the offline tooling as simple as possible for the students, but that's helpful information to have.

**Comment by kotp** [comment]
This is awesome material to post in the forum!  @agentofuser would you be willing to write something up in [the vimscript forum]?

Who knows, after some discussion and exposure to other mentors/maintainers/students, maybe a patch/pull request can be done.  We might even reopen this issue!  (So feel free to link to this issue as a "back story" or "additional discussion" resource!)

[the vimscript forum]: https://forum.exercism.org/c/programming/vimscript/121
